-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains all types with cyclic dependencies (between each other or to itself)
module Linode.TypeAlias where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Linode.Common
import {-# SOURCE #-} Linode.Types.LinodeConfigInterface


-- | Defines an alias for the schema located at @components.schemas.VolumePropertiesSize@ in the specification.
-- 
-- The Volume\'s size, in GiB.
type VolumePropertiesSize = GHC.Types.Int

-- | Defines an alias for the schema located at @components.schemas.VolumePropertiesLabel@ in the specification.
-- 
-- The Volume\'s label is for display purposes only.
type VolumePropertiesLabel = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.RegionPropertiesId@ in the specification.
-- 
-- The unique ID of this Region.
type RegionPropertiesId = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.PersonalAccessTokenPropertiesLabel@ in the specification.
-- 
-- This token\'s label.  This is for display purposes only, but can be used to more easily track what you\'re using each token for.
type PersonalAccessTokenPropertiesLabel = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.PaymentMethodPropertiesIs_default@ in the specification.
-- 
-- Whether this Payment Method is the default method for automatically processing service charges.
type PaymentMethodPropertiesIsDefault = GHC.Types.Bool

-- | Defines an alias for the schema located at @components.schemas.PaginationEnvelopePropertiesResults@ in the specification.
-- 
-- The total number of results.
type PaginationEnvelopePropertiesResults = GHC.Types.Int

-- | Defines an alias for the schema located at @components.schemas.PaginationEnvelopePropertiesPages@ in the specification.
-- 
-- The total number of [pages](\/docs\/api\/\#pagination).
type PaginationEnvelopePropertiesPages = GHC.Types.Int

-- | Defines an alias for the schema located at @components.schemas.PaginationEnvelopePropertiesPage@ in the specification.
-- 
-- The current [page](\/docs\/api\/\#pagination).
type PaginationEnvelopePropertiesPage = GHC.Types.Int

-- | Defines an alias for the schema located at @components.schemas.NodeBalancerPropertiesLabel@ in the specification.
-- 
-- This NodeBalancer\'s label. These must be unique on your Account.
type NodeBalancerPropertiesLabel = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.NodeBalancerPropertiesClient_conn_throttle@ in the specification.
-- 
-- Throttle connections per second.  Set to 0 (zero) to disable throttling.
type NodeBalancerPropertiesClientConnThrottle = GHC.Types.Int

-- | Defines an alias for the schema located at @components.schemas.LinodePropertiesTags@ in the specification.
-- 
-- An array of tags applied to this object.  Tags are for organizational purposes only.
type LinodePropertiesTags = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.LinodePropertiesLabel@ in the specification.
-- 
-- The Linode\'s label is for display purposes only. If no label is provided for a Linode,
-- a default will be assigned.
-- 
-- Linode labels have the following constraints:
-- 
--   * Must begin and end with an alphanumeric character.
--   * May only consist of alphanumeric characters, dashes (\`-\`), underscores (\`_\`) or periods (\`.\`).
--   * Cannot have two dashes (\`--\`), underscores (\`__\`) or periods (\`..\`) in a row.
type LinodePropertiesLabel = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.LinodePropertiesGroup@ in the specification.
-- 
-- A deprecated property denoting a group label for this Linode.
type LinodePropertiesGroup = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.LKENodePoolRequestBodyPropertiesCount@ in the specification.
-- 
-- The number of nodes in the Node Pool.
type LKENodePoolRequestBodyPropertiesCount = GHC.Types.Int

-- | Defines an alias for the schema located at @components.schemas.LKENodePoolPropertiesType@ in the specification.
-- 
-- The Linode Type for all of the nodes in the Node Pool.
type LKENodePoolPropertiesType = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.LKENodePoolPropertiesTags@ in the specification.
-- 
-- An array of tags applied to this object. Tags are for organizational purposes only.
type LKENodePoolPropertiesTags = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.LKENodePoolPropertiesCount@ in the specification.
-- 
-- The number of nodes in the Node Pool.
type LKENodePoolPropertiesCount = GHC.Types.Int

-- | Defines an alias for the schema located at @components.schemas.LKEClusterPropertiesUpdated@ in the specification.
-- 
-- When this Kubernetes cluster was updated.
type LKEClusterPropertiesUpdated = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.LKEClusterPropertiesTags@ in the specification.
-- 
-- An array of tags applied to the Kubernetes cluster. Tags are for organizational purposes only.
type LKEClusterPropertiesTags = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.LKEClusterPropertiesRegion@ in the specification.
-- 
-- This Kubernetes cluster\'s location.
type LKEClusterPropertiesRegion = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.LKEClusterPropertiesLabel@ in the specification.
-- 
-- This Kubernetes cluster\'s unique label for display purposes only.
-- Labels have the following constraints:
-- 
--   * UTF-8 characters will be returned by the API using escape
--     sequences of their Unicode code points. For example, the
--     Japanese character *か* is 3 bytes in UTF-8 (\`0xE382AB\`). Its
--     Unicode code point is 2 bytes (\`0x30AB\`). APIv4 supports this
--     character and the API will return it as the escape sequence
--     using six 1 byte characters which represent 2 bytes of Unicode
--     code point (\`\"\\u30ab\"\`).
--   * 4 byte UTF-8 characters are not supported.
--   * If the label is entirely composed of UTF-8 characters, the API
--     response will return the code points using up to 193 1 byte
--     characters.
type LKEClusterPropertiesLabel = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.LKEClusterPropertiesK8s_version@ in the specification.
-- 
-- The desired Kubernetes version for this Kubernetes cluster in the format of &lt;major&gt;.&lt;minor&gt;, and the latest supported patch version will be deployed.
type LKEClusterPropertiesK8sVersion = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.LKEClusterPropertiesCreated@ in the specification.
-- 
-- When this Kubernetes cluster was created.
type LKEClusterPropertiesCreated = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.FirewallPropertiesTags@ in the specification.
-- 
-- An array of tags applied to this object. Tags are for organizational purposes only.
type FirewallPropertiesTags = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.FirewallPropertiesLabel@ in the specification.
-- 
-- The Firewall\'s label, for display purposes only.
-- 
-- Firewall labels have the following constraints:
-- 
--   * Must begin and end with an alphanumeric character.
--   * May only consist of alphanumeric characters, dashes (\`-\`), underscores (\`_\`) or periods (\`.\`).
--   * Cannot have two dashes (\`--\`), underscores (\`__\`) or periods (\`..\`) in a row.
--   * Must be between 3 and 32 characters.
--   * Must be unique.
type FirewallPropertiesLabel = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.DiskRequestPropertiesStackscript_id@ in the specification.
-- 
-- A StackScript ID that will cause the referenced StackScript to be run during
-- deployment of this Linode. A compatible \`image\` is required to use a
-- StackScript. To get a list of available StackScript and their permitted Images
-- see [\/stackscripts](\/docs\/api\/stackscripts\/\#stackscripts-list).
-- This field cannot be used when deploying from a Backup or a Private Image.
type DiskRequestPropertiesStackscriptId = GHC.Types.Int

-- | Defines an alias for the schema located at @components.schemas.DiskRequestPropertiesStackscript_data@ in the specification.
-- 
-- This field is required only if the StackScript being deployed requires input
-- data from the User for successful completion. See
-- [User Defined Fields (UDFs)](\/docs\/guides\/writing-scripts-for-use-with-linode-stackscripts-a-tutorial\/\#user-defined-fields-udfs)
-- for more details. This field is required to be valid JSON.
type DiskRequestPropertiesStackscriptData = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.DiskRequestPropertiesRoot_pass@ in the specification.
-- 
-- This sets the root user\'s password on a newly-created Linode Disk when deploying from an Image.
-- 
-- * **Required** when creating a Linode Disk from an Image, including when using a StackScript.
-- 
-- * Must meet a password strength score requirement that is calculated internally by the API.
-- If the strength requirement is not met, you will receive a \`Password does not meet strength requirement\` error.
type DiskRequestPropertiesRootPass = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.DiskRequestPropertiesImage@ in the specification.
-- 
-- An Image ID to deploy the Linode Disk from.
-- 
-- Access the Images List ([GET \/images](\/docs\/api\/images\/\#images-list)) endpoint with authentication to view
-- all available Images. Official Linode Images start with \`linode\/\`, while your Account\'s Images start with \`private\/\`. Creating
-- a disk from a Private Image requires \`read_only\` or \`read_write\` permissions for that Image. Access the User\'s
-- Grant Update ([PUT \/account\/users\/{username}\/grants](\/docs\/api\/account\/\#users-grants-update)) endpoint to
-- adjust permissions for an Account Image.
type DiskRequestPropertiesImage = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.DiskRequestPropertiesAuthorized_users@ in the specification.
-- 
-- A list of usernames. If the usernames have associated SSH keys, the keys will be appended to the root users \`~\/.ssh\/authorized_keys\` file automatically when deploying from an Image.
type DiskRequestPropertiesAuthorizedUsers = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.DiskRequestPropertiesAuthorized_keys@ in the specification.
-- 
-- A list of public SSH keys that will be automatically appended
-- to the root user\'s \`~\/.ssh\/authorized_keys\` file when deploying from an Image.
type DiskRequestPropertiesAuthorizedKeys = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.DiskPropertiesLabel@ in the specification.
-- 
-- The Disk\'s label is for display purposes only.
type DiskPropertiesLabel = Data.Text.Internal.Text

-- | Defines an alias for the schema located at @components.schemas.StatsDataUnavailable@ in the specification.
-- 
-- An array of error messages if managed stats are unavaliable.
type StatsDataUnavailable = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.LinodeConfigInterfaces@ in the specification.
-- 
-- An array of Network Interfaces to add to this Linode\'s Configuration Profile.
-- 
-- Up to three interface objects can be entered in this array. The position in the array determines the interface to which the settings apply:
-- 
-- - First\/0:  eth0
-- - Second\/1: eth1
-- - Third\/2:  eth2
-- 
-- When updating a Linode\'s interfaces, *each interface must be redefined*. An empty interfaces array results in a default public interface configuration only.
-- 
-- If no public interface is configured, public IP addresses are still assigned to the Linode but will not be usable without manual configuration.
-- 
-- **Note:** Changes to Linode interface configurations can be enabled by rebooting the Linode.
-- 
-- **Note:** Only Next Generation Network (NGN) data centers support VLANs. Use the Regions ([\/regions](\/docs\/api\/regions\/)) endpoint to view the capabilities of data center regions.
-- If a VLAN is attached to your Linode and you attempt to migrate or clone it to a non-NGN data center,
-- the migration or cloning will not initiate. If a Linode cannot be migrated because of an incompatibility,
-- you will be prompted to select a different data center or contact support.
-- 
-- **Note:** See our guide on [Getting Started with VLANs](\/docs\/guides\/getting-started-with-vlans\/) to view additional [limitations](\/docs\/guides\/getting-started-with-vlans\/\#limitations).
type LinodeConfigInterfaces = [LinodeConfigInterface]
