-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema Account
module Linode.Types.Account where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Linode.Common
import Linode.TypeAlias
import {-# SOURCE #-} Linode.Types.Promotion

-- | Defines the object schema located at @components.schemas.Account@ in the specification.
-- 
-- Account object
data Account = Account {
  -- | active_promotions
  accountActivePromotions :: (GHC.Maybe.Maybe ([Promotion]))
  -- | active_since: The datetime of when the account was activated.
  , accountActiveSince :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | address_1: First line of this Account\'s billing address.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 64
  , accountAddress_1 :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | address_2: Second line of this Account\'s billing address.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 64
  , accountAddress_2 :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | balance: This Account\'s balance, in US dollars.
  , accountBalance :: (GHC.Maybe.Maybe GHC.Types.Double)
  -- | balance_uninvoiced: This Account\'s current estimated invoice in US dollars. This is not your final invoice balance. Transfer charges are not included in the estimate.
  , accountBalanceUninvoiced :: (GHC.Maybe.Maybe GHC.Types.Double)
  -- | capabilities: A list of capabilities your account supports.
  , accountCapabilities :: (GHC.Maybe.Maybe ([Data.Text.Internal.Text]))
  -- | city: The city for this Account\'s billing address.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 24
  , accountCity :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | company: The company name associated with this Account.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 128
  , accountCompany :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | country: The two-letter ISO 3166 country code of this Account\'s billing address.
  , accountCountry :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | credit_card: Credit Card information associated with this Account.
  , accountCreditCard :: (GHC.Maybe.Maybe AccountCreditCard')
  -- | email: The email address of the person associated with this Account.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 128
  , accountEmail :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | euuid: An external unique identifier for this account.
  , accountEuuid :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | first_name: The first name of the person associated with this Account.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 50
  , accountFirstName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | last_name: The last name of the person associated with this Account.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 50
  , accountLastName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | phone: The phone number associated with this Account.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 32
  , accountPhone :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | state: If billing address is in the United States, this is the State portion of the Account\'s billing address. If the address is outside the US, this is the Province associated with the Account\'s billing address.
  -- 
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 24
  , accountState :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | tax_id: The tax identification number associated with this Account, for tax calculations in some countries. If you do not live in a country that collects tax, this should be \`null\`.
  -- 
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 100
  , accountTaxId :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | zip: The zip code of this Account\'s billing address. The following restrictions apply:
  -- 
  -- - May only consist of letters, numbers, spaces, and hyphens.
  -- - Must not contain more than 9 letter or number characters.
  , accountZip :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Account
    where toJSON obj = Data.Aeson.Types.Internal.object ("active_promotions" Data.Aeson.Types.ToJSON..= accountActivePromotions obj : "active_since" Data.Aeson.Types.ToJSON..= accountActiveSince obj : "address_1" Data.Aeson.Types.ToJSON..= accountAddress_1 obj : "address_2" Data.Aeson.Types.ToJSON..= accountAddress_2 obj : "balance" Data.Aeson.Types.ToJSON..= accountBalance obj : "balance_uninvoiced" Data.Aeson.Types.ToJSON..= accountBalanceUninvoiced obj : "capabilities" Data.Aeson.Types.ToJSON..= accountCapabilities obj : "city" Data.Aeson.Types.ToJSON..= accountCity obj : "company" Data.Aeson.Types.ToJSON..= accountCompany obj : "country" Data.Aeson.Types.ToJSON..= accountCountry obj : "credit_card" Data.Aeson.Types.ToJSON..= accountCreditCard obj : "email" Data.Aeson.Types.ToJSON..= accountEmail obj : "euuid" Data.Aeson.Types.ToJSON..= accountEuuid obj : "first_name" Data.Aeson.Types.ToJSON..= accountFirstName obj : "last_name" Data.Aeson.Types.ToJSON..= accountLastName obj : "phone" Data.Aeson.Types.ToJSON..= accountPhone obj : "state" Data.Aeson.Types.ToJSON..= accountState obj : "tax_id" Data.Aeson.Types.ToJSON..= accountTaxId obj : "zip" Data.Aeson.Types.ToJSON..= accountZip obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("active_promotions" Data.Aeson.Types.ToJSON..= accountActivePromotions obj) GHC.Base.<> (("active_since" Data.Aeson.Types.ToJSON..= accountActiveSince obj) GHC.Base.<> (("address_1" Data.Aeson.Types.ToJSON..= accountAddress_1 obj) GHC.Base.<> (("address_2" Data.Aeson.Types.ToJSON..= accountAddress_2 obj) GHC.Base.<> (("balance" Data.Aeson.Types.ToJSON..= accountBalance obj) GHC.Base.<> (("balance_uninvoiced" Data.Aeson.Types.ToJSON..= accountBalanceUninvoiced obj) GHC.Base.<> (("capabilities" Data.Aeson.Types.ToJSON..= accountCapabilities obj) GHC.Base.<> (("city" Data.Aeson.Types.ToJSON..= accountCity obj) GHC.Base.<> (("company" Data.Aeson.Types.ToJSON..= accountCompany obj) GHC.Base.<> (("country" Data.Aeson.Types.ToJSON..= accountCountry obj) GHC.Base.<> (("credit_card" Data.Aeson.Types.ToJSON..= accountCreditCard obj) GHC.Base.<> (("email" Data.Aeson.Types.ToJSON..= accountEmail obj) GHC.Base.<> (("euuid" Data.Aeson.Types.ToJSON..= accountEuuid obj) GHC.Base.<> (("first_name" Data.Aeson.Types.ToJSON..= accountFirstName obj) GHC.Base.<> (("last_name" Data.Aeson.Types.ToJSON..= accountLastName obj) GHC.Base.<> (("phone" Data.Aeson.Types.ToJSON..= accountPhone obj) GHC.Base.<> (("state" Data.Aeson.Types.ToJSON..= accountState obj) GHC.Base.<> (("tax_id" Data.Aeson.Types.ToJSON..= accountTaxId obj) GHC.Base.<> ("zip" Data.Aeson.Types.ToJSON..= accountZip obj)))))))))))))))))))
instance Data.Aeson.Types.FromJSON.FromJSON Account
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "Account" (\obj -> ((((((((((((((((((GHC.Base.pure Account GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "active_promotions")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "active_since")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "address_1")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "address_2")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "balance")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "balance_uninvoiced")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "capabilities")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "city")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "company")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "country")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "credit_card")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "email")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "euuid")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "first_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "last_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "phone")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "state")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "tax_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "zip"))
-- | Create a new 'Account' with all required fields.
mkAccount :: Account
mkAccount = Account{accountActivePromotions = GHC.Maybe.Nothing,
                    accountActiveSince = GHC.Maybe.Nothing,
                    accountAddress_1 = GHC.Maybe.Nothing,
                    accountAddress_2 = GHC.Maybe.Nothing,
                    accountBalance = GHC.Maybe.Nothing,
                    accountBalanceUninvoiced = GHC.Maybe.Nothing,
                    accountCapabilities = GHC.Maybe.Nothing,
                    accountCity = GHC.Maybe.Nothing,
                    accountCompany = GHC.Maybe.Nothing,
                    accountCountry = GHC.Maybe.Nothing,
                    accountCreditCard = GHC.Maybe.Nothing,
                    accountEmail = GHC.Maybe.Nothing,
                    accountEuuid = GHC.Maybe.Nothing,
                    accountFirstName = GHC.Maybe.Nothing,
                    accountLastName = GHC.Maybe.Nothing,
                    accountPhone = GHC.Maybe.Nothing,
                    accountState = GHC.Maybe.Nothing,
                    accountTaxId = GHC.Maybe.Nothing,
                    accountZip = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.Account.properties.credit_card@ in the specification.
-- 
-- Credit Card information associated with this Account.
data AccountCreditCard' = AccountCreditCard' {
  -- | expiry: The expiration month and year of the credit card.
  accountCreditCard'Expiry :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | last_four: The last four digits of the credit card associated with this Account.
  , accountCreditCard'LastFour :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON AccountCreditCard'
    where toJSON obj = Data.Aeson.Types.Internal.object ("expiry" Data.Aeson.Types.ToJSON..= accountCreditCard'Expiry obj : "last_four" Data.Aeson.Types.ToJSON..= accountCreditCard'LastFour obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("expiry" Data.Aeson.Types.ToJSON..= accountCreditCard'Expiry obj) GHC.Base.<> ("last_four" Data.Aeson.Types.ToJSON..= accountCreditCard'LastFour obj))
instance Data.Aeson.Types.FromJSON.FromJSON AccountCreditCard'
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "AccountCreditCard'" (\obj -> (GHC.Base.pure AccountCreditCard' GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "expiry")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "last_four"))
-- | Create a new 'AccountCreditCard'' with all required fields.
mkAccountCreditCard' :: AccountCreditCard'
mkAccountCreditCard' = AccountCreditCard'{accountCreditCard'Expiry = GHC.Maybe.Nothing,
                                          accountCreditCard'LastFour = GHC.Maybe.Nothing}
