-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE DeriveGeneric #-}

-- | Contains the types generated from the schema ObjectStorageObject
module Linode.Types.ObjectStorageObject where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Generics
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Linode.Common

-- | Defines the data type for the schema ObjectStorageObject
-- 
-- An Object in Object Storage, or a \"prefix\" that contains one or more objects when a \`delimiter\` is used.
data ObjectStorageObject = ObjectStorageObject {
  -- | etag: An MD-5 hash of the object. \`null\` if this object represents a prefix.
  objectStorageObjectEtag :: (GHC.Base.Maybe Data.Text.Internal.Text)
  -- | is_truncated: Designates if there is another page of bucket objects.
  , objectStorageObjectIs_truncated :: (GHC.Base.Maybe GHC.Types.Bool)
  -- | last_modified: The date and time this object was last modified. \`null\` if this object represents a prefix.
  , objectStorageObjectLast_modified :: (GHC.Base.Maybe Data.Text.Internal.Text)
  -- | name: The name of this object or prefix.
  , objectStorageObjectName :: (GHC.Base.Maybe Data.Text.Internal.Text)
  -- | next_marker: Returns the value you should pass to the \`marker\` query parameter to get the next page of objects. If there is no next page, \`null\` will be returned.
  , objectStorageObjectNext_marker :: (GHC.Base.Maybe Data.Text.Internal.Text)
  -- | owner: The owner of this object, as a UUID. \`null\` if this object represents a prefix.
  , objectStorageObjectOwner :: (GHC.Base.Maybe Data.Text.Internal.Text)
  -- | size: The size of this object, in bytes. \`null\` if this object represents a prefix.
  , objectStorageObjectSize :: (GHC.Base.Maybe GHC.Integer.Type.Integer)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.ToJSON ObjectStorageObject
    where toJSON obj = Data.Aeson.object ((Data.Aeson..=) "etag" (objectStorageObjectEtag obj) : (Data.Aeson..=) "is_truncated" (objectStorageObjectIs_truncated obj) : (Data.Aeson..=) "last_modified" (objectStorageObjectLast_modified obj) : (Data.Aeson..=) "name" (objectStorageObjectName obj) : (Data.Aeson..=) "next_marker" (objectStorageObjectNext_marker obj) : (Data.Aeson..=) "owner" (objectStorageObjectOwner obj) : (Data.Aeson..=) "size" (objectStorageObjectSize obj) : [])
          toEncoding obj = Data.Aeson.pairs ((Data.Aeson..=) "etag" (objectStorageObjectEtag obj) GHC.Base.<> ((Data.Aeson..=) "is_truncated" (objectStorageObjectIs_truncated obj) GHC.Base.<> ((Data.Aeson..=) "last_modified" (objectStorageObjectLast_modified obj) GHC.Base.<> ((Data.Aeson..=) "name" (objectStorageObjectName obj) GHC.Base.<> ((Data.Aeson..=) "next_marker" (objectStorageObjectNext_marker obj) GHC.Base.<> ((Data.Aeson..=) "owner" (objectStorageObjectOwner obj) GHC.Base.<> (Data.Aeson..=) "size" (objectStorageObjectSize obj)))))))
instance Data.Aeson.Types.FromJSON.FromJSON ObjectStorageObject
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "ObjectStorageObject" (\obj -> ((((((GHC.Base.pure ObjectStorageObject GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "etag")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "is_truncated")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "last_modified")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "next_marker")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "owner")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "size"))