-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema Payment
module Linode.Types.Payment where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Linode.Common
import Linode.TypeAlias

-- | Defines the object schema located at @components.schemas.Payment@ in the specification.
-- 
-- Payment object response.
data Payment = Payment {
  -- | date: When the Payment was made.
  paymentDate :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | id: The unique ID of the Payment.
  , paymentId :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | usd: The amount, in US dollars, of the Payment.
  , paymentUsd :: (GHC.Maybe.Maybe GHC.Types.Int)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Payment
    where toJSON obj = Data.Aeson.Types.Internal.object ("date" Data.Aeson.Types.ToJSON..= paymentDate obj : "id" Data.Aeson.Types.ToJSON..= paymentId obj : "usd" Data.Aeson.Types.ToJSON..= paymentUsd obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("date" Data.Aeson.Types.ToJSON..= paymentDate obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= paymentId obj) GHC.Base.<> ("usd" Data.Aeson.Types.ToJSON..= paymentUsd obj)))
instance Data.Aeson.Types.FromJSON.FromJSON Payment
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "Payment" (\obj -> ((GHC.Base.pure Payment GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "date")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "usd"))
-- | Create a new 'Payment' with all required fields.
mkPayment :: Payment
mkPayment = Payment{paymentDate = GHC.Maybe.Nothing,
                    paymentId = GHC.Maybe.Nothing,
                    paymentUsd = GHC.Maybe.Nothing}
