-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE DeriveGeneric #-}

-- | Contains the types generated from the schema PayPalData
module Linode.Types.PayPalData where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Generics
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Linode.Common

-- | Defines the data type for the schema PayPalData
-- 
-- PayPal information.
data PayPalData = PayPalData {
  -- | email: The email address associated with your PayPal account.
  payPalDataEmail :: (GHC.Base.Maybe Data.Text.Internal.Text)
  -- | paypal_id: PayPal Merchant ID associated with your PayPal account.
  , payPalDataPaypal_id :: (GHC.Base.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.ToJSON PayPalData
    where toJSON obj = Data.Aeson.object ((Data.Aeson..=) "email" (payPalDataEmail obj) : (Data.Aeson..=) "paypal_id" (payPalDataPaypal_id obj) : [])
          toEncoding obj = Data.Aeson.pairs ((Data.Aeson..=) "email" (payPalDataEmail obj) GHC.Base.<> (Data.Aeson..=) "paypal_id" (payPalDataPaypal_id obj))
instance Data.Aeson.Types.FromJSON.FromJSON PayPalData
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PayPalData" (\obj -> (GHC.Base.pure PayPalData GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "email")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "paypal_id"))