-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema StatsData
module Linode.Types.StatsData where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Linode.Common
import Linode.TypeAlias

-- | Defines the object schema located at @components.schemas.StatsData@ in the specification.
-- 
-- A stat data point.
data StatsData = StatsData {
  -- | x: A stats graph data point.
  statsDataX :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | y: A stats graph data point.
  , statsDataY :: (GHC.Maybe.Maybe GHC.Types.Int)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON StatsData
    where toJSON obj = Data.Aeson.Types.Internal.object ("x" Data.Aeson.Types.ToJSON..= statsDataX obj : "y" Data.Aeson.Types.ToJSON..= statsDataY obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("x" Data.Aeson.Types.ToJSON..= statsDataX obj) GHC.Base.<> ("y" Data.Aeson.Types.ToJSON..= statsDataY obj))
instance Data.Aeson.Types.FromJSON.FromJSON StatsData
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "StatsData" (\obj -> (GHC.Base.pure StatsData GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "x")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "y"))
-- | Create a new 'StatsData' with all required fields.
mkStatsData :: StatsData
mkStatsData = StatsData{statsDataX = GHC.Maybe.Nothing,
                        statsDataY = GHC.Maybe.Nothing}
