-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE DeriveGeneric #-}

-- | Contains the types generated from the schema Transfer
module Linode.Types.Transfer where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Generics
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Linode.Common

-- | Defines the data type for the schema Transfer
-- 
-- An object representing your network utilization for the current month, in Gigabytes.
data Transfer = Transfer {
  -- | billable: The amount of your transfer pool that is billable this billing cycle.
  transferBillable :: (GHC.Base.Maybe GHC.Integer.Type.Integer)
  -- | quota: The amount of network usage allowed this billing cycle.
  , transferQuota :: (GHC.Base.Maybe GHC.Integer.Type.Integer)
  -- | used: The amount of network usage you have used this billing cycle.
  , transferUsed :: (GHC.Base.Maybe GHC.Integer.Type.Integer)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.ToJSON Transfer
    where toJSON obj = Data.Aeson.object ((Data.Aeson..=) "billable" (transferBillable obj) : (Data.Aeson..=) "quota" (transferQuota obj) : (Data.Aeson..=) "used" (transferUsed obj) : [])
          toEncoding obj = Data.Aeson.pairs ((Data.Aeson..=) "billable" (transferBillable obj) GHC.Base.<> ((Data.Aeson..=) "quota" (transferQuota obj) GHC.Base.<> (Data.Aeson..=) "used" (transferUsed obj)))
instance Data.Aeson.Types.FromJSON.FromJSON Transfer
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "Transfer" (\obj -> ((GHC.Base.pure Transfer GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "billable")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "quota")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:? "used"))